# After you've edited this file, remove the following line to allow
# `yesod keter` to build your bundle.

# A Keter app is composed of 1 or more stanzas. The main stanza will define our
# web application. See the Keter documentation for more information on
# available stanzas.
stanzas:
  exec: ../dist/build/justtext/justtext
  args:
    - production
  host: www.ttxtt.io
  postgres: true
