Default: &defaults
  database: justtext.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: justtext_test.sqlite3
  <<: *defaults

Staging:
  database: justtext_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: justtext_production.sqlite3
  poolsize: 100
  <<: *defaults
